[[posts]]
title = "README for wCalc"
description = "The introduction to wCalc"
date = "2025-04-04"
author = "tttiw"
tags = ["wCalc"]
file = "wcalc-readme.md"

[[posts]]
title = "Code Templates"
description = "Code templates for wCalc"
date = "2025-03-28"
tags = ["wCalc"]
file = "code-templates.md"

[[posts]]
title = "wCalc API Reference"
description = "The API reference for wCalc"
date = "2025-04-04"
author = "tttiw"
tags = ["wCalc"]
file = "wcalc-api.md"

[[posts]]
title = "Markdown Test"
description = "For debugging"
date = "2025-03-15"
author = "ChatGPT"
tags = ["Debug"]
file = "markdown-test.md"

[[posts]]
title = "Catalog"
description = "The catalog"
date = "2025-03-16"
author = "tttiw"
tags = ["Illusory Dept."]
file = "list.md"